# Use Node.js 16-alpine for compatibility
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json to the working directory
COPY package.json ./

# RUN apt-get update && apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic && \
#     rm -rf /var/lib/apt/lists/*
# Install dependencies

# RUN apt-get update && apt-get install -y \
#   texlive-xetex \
#   && rm -rf /var/lib/apt/lists/*
  
RUN npm install --legacy-peer-deps

# Copy the remaining application files
COPY . .

# Expose the application port
EXPOSE 8080

# Set the command to run migrations and start the server
# CMD ["sh", "-c", "npx prisma migrate dev && npm run server"]
CMD ["npm", "run", "client"]
